/**
 * @fileoverview Workflow Export Utilities for AEMFlow
 *
 * This module provides comprehensive export and import functionality for
 * AEMFlow workflows. It supports multiple output formats suitable for
 * different use cases:
 *
 * - **AEM XML**: Native AEM workflow model format for direct deployment
 * - **JSON**: Portable format for backup, transfer, and version control
 * - **YAML**: Human-readable configuration format
 * - **Markdown**: Documentation generation with embedded Mermaid diagrams
 * - **Mermaid**: Standalone diagram syntax for wikis and docs
 *
 * @module utils/exporters
 * @author AEMFlow Team
 * @version 2.0.0
 * @license MIT
 *
 * @example
 * // Export workflow to AEM XML
 * import { exportToAEMXML, downloadFile } from './exporters';
 *
 * const xml = exportToAEMXML(nodes, edges, {
 *   workflowName: 'Content Approval',
 *   author: 'John Doe'
 * });
 * downloadFile(xml, 'workflow.xml', 'application/xml');
 *
 * @example
 * // Import workflow from JSON
 * import { importFromJSON } from './exporters';
 *
 * const { nodes, edges } = importFromJSON(jsonString);
 */

import { Node, Edge } from '@reactflow/core';

/**
 * Configuration options for workflow export operations.
 *
 * @interface ExportOptions
 * @property {boolean} [includeMetadata=true] - Include workflow metadata (name, author, timestamps)
 * @property {boolean} [includePositions=true] - Include node position coordinates
 * @property {boolean} [includeDescription=false] - Include step descriptions
 * @property {boolean} [prettyPrint=true] - Format output with indentation (JSON/YAML)
 * @property {string} [workflowName='Custom Workflow'] - Name of the workflow
 * @property {string} [workflowDescription=''] - Description of the workflow
 * @property {string} [author='AEMFlow'] - Author attribution
 *
 * @example
 * const options: ExportOptions = {
 *   workflowName: 'Content Review Process',
 *   author: 'Content Team',
 *   includeMetadata: true,
 *   prettyPrint: true
 * };
 */
export interface ExportOptions {
  /** Include workflow metadata (name, author, timestamps) */
  includeMetadata?: boolean;
  /** Include node position coordinates */
  includePositions?: boolean;
  /** Include step descriptions */
  includeDescription?: boolean;
  /** Format output with indentation (JSON/YAML) */
  prettyPrint?: boolean;
  /** Name of the workflow */
  workflowName?: string;
  /** Description of the workflow */
  workflowDescription?: string;
  /** Author attribution */
  author?: string;
}

// =====================================
// AEM XML Export
// =====================================

/**
 * Exports workflow to Adobe Experience Manager XML format.
 *
 * Generates a complete AEM workflow model XML file that can be directly
 * deployed to an AEM instance. The output follows the CQ workflow component
 * structure with proper JCR node types and namespaces.
 *
 * @param {Node[]} nodes - Array of ReactFlow nodes representing workflow steps
 * @param {Edge[]} edges - Array of ReactFlow edges representing transitions
 * @param {ExportOptions} [options={}] - Export configuration options
 * @returns {string} Complete AEM workflow XML document
 *
 * @example
 * const xml = exportToAEMXML(nodes, edges, {
 *   workflowName: 'Content Approval',
 *   workflowDescription: 'Multi-level content review process',
 *   author: 'Content Team'
 * });
 *
 * @see {@link https://experienceleague.adobe.com/docs/experience-manager-65/developing/extending-aem/extending-workflows/workflows.html|AEM Workflows Documentation}
 */
export const exportToAEMXML = (
  nodes: Node[],
  edges: Edge[],
  options: ExportOptions = {}
): string => {
  const {
    workflowName = 'Custom Workflow',
    workflowDescription = 'Generated by AEMFlow',
    author = 'AEMFlow',
  } = options;

  const startNode = nodes.find(n => n.type === 'startEnd' && n.data?.isStart) || nodes[0];
  const endNode = nodes.find(n => n.type === 'startEnd' && !n.data?.isStart) || nodes[nodes.length - 1];
  
  // Filter out the nodes we will explicitly handle as start/end
  const otherNodes = nodes.filter(n => n.id !== startNode.id && n.id !== endNode.id);
  
  // Create a mapping of ReactFlow IDs to AEM node names (node0, node1, etc.)
  const nodeMapping: Record<string, string> = {};
  nodeMapping[startNode.id] = 'node0';
  otherNodes.forEach((node, i) => {
    nodeMapping[node.id] = `node${i + 1}`;
  });
  nodeMapping[endNode.id] = `node${otherNodes.length + 1}`;

  let xml = `<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0"
          xmlns:cq="http://www.day.com/jcr/cq/1.0"
          xmlns:jcr="http://www.jcp.org/jcr/1.0"
          xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
          jcr:primaryType="cq:Page">
    <jcr:content
        cq:designPath="/libs/settings/wcm/designs/default"
        cq:template="/libs/cq/workflow/templates/model"
        jcr:primaryType="cq:PageContent"
        jcr:title="${escapeXml(workflowName)}"
        sling:resourceType="cq/workflow/components/pages/model">
        <flow
            jcr:primaryType="nt:unstructured"
            sling:resourceType="foundation/components/parsys">
`;

  // Standard flow nodes for the visual parsys (simplified)
  nodes.forEach((node) => {
    const nodeId = sanitizeId(node.id);
    const nodeConfig = getAEMNodeConfig(node);
    xml += `            <${nodeId}
                jcr:primaryType="nt:unstructured"
                jcr:title="${escapeXml(node.data?.label || node.id)}"
                sling:resourceType="${nodeConfig.resourceType}"/>\n`;
  });

  xml += `        </flow>
        <model
            jcr:primaryType="nt:unstructured"
            sling:resourceType="cq/workflow/components/model"
            description="${escapeXml(workflowDescription)}"
            title="${escapeXml(workflowName)}">
            <nodes jcr:primaryType="nt:unstructured">
`;

  // Export internal nodes for the engine
  nodes.forEach((node) => {
    const aemNodeName = nodeMapping[node.id];
    const nodeConfig = getAEMNodeConfig(node);
    
    xml += `                <${aemNodeName}
                    jcr:primaryType="nt:unstructured"
                    jcr:title="${escapeXml(node.data?.label || node.id)}"
                    jcr:description="${escapeXml(node.data?.description || '')}"
                    type="${node.type === 'startEnd' ? (node.data?.isStart ? 'START' : 'END') : 'STEP'}"
                    sling:resourceType="${nodeConfig.resourceType}">
                    <metaData jcr:primaryType="nt:unstructured"`;
    
    // Add attributes to metadata
    Object.entries(nodeConfig.attributes).forEach(([key, value]) => {
      xml += `\n                        ${key}="${escapeXml(String(value))}"`;
    });
    
    xml += `/>
                </${aemNodeName}>\n`;
  });

  xml += `            </nodes>
            <transitions jcr:primaryType="nt:unstructured">
`;

  // Export transitions
  edges.forEach((edge, i) => {
    const fromNode = nodeMapping[edge.source];
    const toNode = nodeMapping[edge.target];
    if (fromNode && toNode) {
      xml += `                <node${i}_node${i}
                    jcr:primaryType="nt:unstructured"
                    from="${fromNode}"
                    to="${toNode}"
                    rule="${escapeXml(typeof edge.label === 'string' ? edge.label : '')}"/>\n`;
    }
  });

  xml += `            </transitions>
        </model>
    </jcr:content>
</jcr:root>`;

  return xml;
};

// =====================================
// JSON Export
// =====================================

/**
 * Exports workflow to JSON format for backup and transfer.
 *
 * Creates a portable JSON representation of the workflow that can be:
 * - Stored in version control systems
 * - Transferred between AEMFlow instances
 * - Used for workflow backup and restore
 * - Processed by external tools
 *
 * @param {Node[]} nodes - Array of ReactFlow nodes representing workflow steps
 * @param {Edge[]} edges - Array of ReactFlow edges representing transitions
 * @param {ExportOptions} [options={}] - Export configuration options
 * @returns {string} JSON string representation of the workflow
 *
 * @example
 * const json = exportToJSON(nodes, edges, {
 *   includePositions: true,
 *   prettyPrint: true
 * });
 *
 * // Save to file
 * downloadFile(json, 'workflow.json', 'application/json');
 *
 * @throws {Error} Never throws - returns empty workflow if nodes/edges are invalid
 */
export const exportToJSON = (
  nodes: Node[],
  edges: Edge[],
  options: ExportOptions = {}
): string => {
  const {
    includeMetadata = true,
    includePositions = true,
    prettyPrint = true,
    workflowName = 'Custom Workflow',
    workflowDescription = '',
    author = 'AEMFlow',
  } = options;

  const workflow: any = {
    version: '1.0',
    format: 'aemflow-json',
  };

  if (includeMetadata) {
    workflow.metadata = {
      name: workflowName,
      description: workflowDescription,
      author,
      createdAt: new Date().toISOString(),
      nodeCount: nodes.length,
      edgeCount: edges.length,
    };
  }

  workflow.nodes = nodes.map(node => {
    const exportNode: any = {
      id: node.id,
      type: node.type,
      data: { ...node.data },
    };

    if (includePositions) {
      exportNode.position = node.position;
    }

    return exportNode;
  });

  workflow.edges = edges.map(edge => ({
    id: edge.id,
    source: edge.source,
    target: edge.target,
    sourceHandle: edge.sourceHandle,
    targetHandle: edge.targetHandle,
    label: edge.label,
  }));

  return prettyPrint
    ? JSON.stringify(workflow, null, 2)
    : JSON.stringify(workflow);
};

// =====================================
// YAML Export
// =====================================

/**
 * Exports workflow to YAML format for human-readable configuration.
 *
 * YAML format is ideal for:
 * - Human review and editing
 * - Configuration management systems
 * - Documentation alongside code
 * - Diff-friendly version control
 *
 * @param {Node[]} nodes - Array of ReactFlow nodes representing workflow steps
 * @param {Edge[]} edges - Array of ReactFlow edges representing transitions
 * @param {ExportOptions} [options={}] - Export configuration options
 * @returns {string} YAML representation of the workflow
 *
 * @example
 * const yaml = exportToYAML(nodes, edges, {
 *   workflowName: 'Content Approval',
 *   includePositions: false // Cleaner YAML without positions
 * });
 */
export const exportToYAML = (
  nodes: Node[],
  edges: Edge[],
  options: ExportOptions = {}
): string => {
  const {
    includeMetadata = true,
    includePositions = false,
    workflowName = 'Custom Workflow',
    workflowDescription = '',
    author = 'AEMFlow',
  } = options;

  let yaml = `# AEMFlow Workflow Definition
# Generated: ${new Date().toISOString()}

version: "1.0"
format: aemflow-yaml

`;

  if (includeMetadata) {
    yaml += `metadata:
  name: "${workflowName}"
  description: "${workflowDescription}"
  author: "${author}"
  nodeCount: ${nodes.length}
  edgeCount: ${edges.length}

`;
  }

  yaml += `nodes:\n`;

  nodes.forEach(node => {
    yaml += `  - id: "${node.id}"
    type: ${node.type}
    label: "${node.data?.label || ''}"`;

    if (node.data?.description) {
      yaml += `\n    description: "${node.data.description}"`;
    }

    if (node.data?.participant) {
      yaml += `\n    participant: "${node.data.participant}"`;
    }

    if (node.data?.isStart !== undefined) {
      yaml += `\n    isStart: ${node.data.isStart}`;
    }

    if (includePositions) {
      yaml += `\n    position:
      x: ${node.position.x}
      y: ${node.position.y}`;
    }

    yaml += '\n';
  });

  yaml += `\nedges:\n`;

  edges.forEach(edge => {
    yaml += `  - id: "${edge.id}"
    source: "${edge.source}"
    target: "${edge.target}"`;

    if (edge.sourceHandle) {
      yaml += `\n    sourceHandle: "${edge.sourceHandle}"`;
    }

    if (edge.label) {
      yaml += `\n    label: "${edge.label}"`;
    }

    yaml += '\n';
  });

  return yaml;
};

// =====================================
// Markdown Documentation Export
// =====================================

/**
 * Exports workflow as comprehensive Markdown documentation.
 *
 * Generates rich documentation including:
 * - Overview with workflow statistics
 * - Detailed step descriptions grouped by type
 * - Participant responsibility matrix
 * - Embedded Mermaid flow diagram
 * - Connection mappings (from/to)
 *
 * @param {Node[]} nodes - Array of ReactFlow nodes representing workflow steps
 * @param {Edge[]} edges - Array of ReactFlow edges representing transitions
 * @param {ExportOptions} [options={}] - Export configuration options
 * @returns {string} Markdown documentation with embedded Mermaid diagram
 *
 * @example
 * const markdown = exportToMarkdown(nodes, edges, {
 *   workflowName: 'Content Approval Workflow',
 *   workflowDescription: 'Three-level content review process',
 *   author: 'Content Operations Team'
 * });
 *
 * // Render in GitHub, GitLab, or any Mermaid-compatible viewer
 */
export const exportToMarkdown = (
  nodes: Node[],
  edges: Edge[],
  options: ExportOptions = {}
): string => {
  const {
    workflowName = 'Custom Workflow',
    workflowDescription = '',
    author = 'AEMFlow',
  } = options;

  const workflowNodes = nodes.filter(n => n.type !== 'startEnd');
  const branchNodes = nodes.filter(n => n.type === 'branch');
  const participantNodes = nodes.filter(n =>
    n.type === 'aemStep' || n.type === 'participantChooser'
  );

  let md = `# ${workflowName}

${workflowDescription}

---

## Overview

| Metric | Value |
|--------|-------|
| Total Steps | ${workflowNodes.length} |
| Decision Points | ${branchNodes.length} |
| Human Tasks | ${participantNodes.length} |
| Connections | ${edges.length} |
| Generated | ${new Date().toLocaleDateString()} |
| Author | ${author} |

---

## Workflow Steps

`;

  // Group nodes by type
  const nodesByType: Record<string, Node[]> = {};
  workflowNodes.forEach(node => {
    const type = node.type || 'other';
    if (!nodesByType[type]) nodesByType[type] = [];
    nodesByType[type].push(node);
  });

  const typeLabels: Record<string, string> = {
    aemStep: 'Participant Steps',
    processStep: 'Process Steps',
    branch: 'Decision Points',
    emailNotification: 'Notifications',
    damUpdate: 'DAM Operations',
    damMetadata: 'Metadata Operations',
    damTranscode: 'Transcoding Steps',
    formsProcess: 'Form Processing',
    pageActivation: 'Publishing Steps',
    callWorkflow: 'Sub-Workflows',
    participantChooser: 'Dynamic Assignment',
    graniteRouting: 'Routing Steps',
  };

  Object.entries(nodesByType).forEach(([type, typeNodes]) => {
    md += `### ${typeLabels[type] || type}\n\n`;

    typeNodes.forEach(node => {
      md += `#### ${node.data?.label || node.id}\n\n`;

      if (node.data?.description) {
        md += `${node.data.description}\n\n`;
      }

      md += `| Property | Value |\n`;
      md += `|----------|-------|\n`;
      md += `| Type | \`${type}\` |\n`;

      if (node.data?.participant) {
        md += `| Participant | ${node.data.participant} |\n`;
      }

      if (node.data?.timeout) {
        md += `| Timeout | ${node.data.timeout} minutes |\n`;
      }

      if (node.data?.processHandler) {
        md += `| Handler | \`${node.data.processHandler}\` |\n`;
      }

      // Find connections
      const incoming = edges.filter(e => e.target === node.id);
      const outgoing = edges.filter(e => e.source === node.id);

      if (incoming.length > 0) {
        const incomingLabels = incoming.map(e => {
          const sourceNode = nodes.find(n => n.id === e.source);
          return sourceNode?.data?.label || e.source;
        }).join(', ');
        md += `| From | ${incomingLabels} |\n`;
      }

      if (outgoing.length > 0) {
        const outgoingLabels = outgoing.map(e => {
          const targetNode = nodes.find(n => n.id === e.target);
          const label = e.label ? ` (${e.label})` : '';
          return (targetNode?.data?.label || e.target) + label;
        }).join(', ');
        md += `| To | ${outgoingLabels} |\n`;
      }

      md += '\n';
    });
  });

  // Add flow diagram (Mermaid)
  md += `---

## Flow Diagram

\`\`\`mermaid
${generateMermaidDiagram(nodes, edges)}
\`\`\`

---

## Participants

| Participant | Steps |
|-------------|-------|
`;

  const participantSteps: Record<string, string[]> = {};
  nodes.forEach(node => {
    if (node.data?.participant) {
      if (!participantSteps[node.data.participant]) {
        participantSteps[node.data.participant] = [];
      }
      participantSteps[node.data.participant].push(node.data.label || node.id);
    }
  });

  Object.entries(participantSteps).forEach(([participant, steps]) => {
    md += `| ${participant} | ${steps.join(', ')} |\n`;
  });

  md += `
---

*Documentation generated by AEMFlow*
`;

  return md;
};

// =====================================
// Mermaid Diagram Export
// =====================================

/**
 * Generates a Mermaid flowchart diagram from workflow nodes and edges.
 *
 * Creates a visual representation using Mermaid syntax that can be
 * rendered in:
 * - GitHub/GitLab Markdown
 * - Notion, Confluence, and other documentation tools
 * - Mermaid Live Editor
 * - HTML pages with Mermaid.js
 *
 * Node shapes are determined by type:
 * - Start/End: Circle/Double circle
 * - Branch: Diamond (decision)
 * - Process: Parallelogram
 * - Others: Rectangle
 *
 * @param {Node[]} nodes - Array of ReactFlow nodes representing workflow steps
 * @param {Edge[]} edges - Array of ReactFlow edges representing transitions
 * @returns {string} Mermaid flowchart syntax
 *
 * @example
 * const mermaid = generateMermaidDiagram(nodes, edges);
 *
 * // Use in Markdown:
 * // ```mermaid
 * // ${mermaid}
 * // ```
 *
 * @see {@link https://mermaid.js.org/syntax/flowchart.html|Mermaid Flowchart Syntax}
 */
export const generateMermaidDiagram = (
  nodes: Node[],
  edges: Edge[]
): string => {
  let mermaid = 'flowchart TD\n';

  // Define nodes
  nodes.forEach(node => {
    const id = sanitizeMermaidId(node.id);
    const label = node.data?.label || node.id;

    if (node.type === 'startEnd') {
      if (node.data?.isStart) {
        mermaid += `    ${id}((${label}))\n`;
      } else {
        mermaid += `    ${id}(((${label})))\n`;
      }
    } else if (node.type === 'branch') {
      mermaid += `    ${id}{${label}}\n`;
    } else if (node.type === 'processStep' || node.type === 'damUpdate' || node.type === 'damTranscode') {
      mermaid += `    ${id}[/${label}/]\n`;
    } else {
      mermaid += `    ${id}[${label}]\n`;
    }
  });

  mermaid += '\n';

  // Define edges
  edges.forEach(edge => {
    const sourceId = sanitizeMermaidId(edge.source);
    const targetId = sanitizeMermaidId(edge.target);

    if (edge.label) {
      mermaid += `    ${sourceId} -->|${edge.label}| ${targetId}\n`;
    } else {
      mermaid += `    ${sourceId} --> ${targetId}\n`;
    }
  });

  // Add styling
  mermaid += '\n';
  mermaid += '    classDef startEnd fill:#10b981,stroke:#059669,color:#fff\n';
  mermaid += '    classDef branch fill:#8b5cf6,stroke:#7c3aed,color:#fff\n';
  mermaid += '    classDef process fill:#f59e0b,stroke:#d97706,color:#fff\n';
  mermaid += '    classDef participant fill:#3b82f6,stroke:#2563eb,color:#fff\n';

  // Apply classes
  nodes.forEach(node => {
    const id = sanitizeMermaidId(node.id);
    if (node.type === 'startEnd') {
      mermaid += `    class ${id} startEnd\n`;
    } else if (node.type === 'branch') {
      mermaid += `    class ${id} branch\n`;
    } else if (node.type === 'processStep' || node.type === 'damUpdate') {
      mermaid += `    class ${id} process\n`;
    } else if (node.type === 'aemStep' || node.type === 'participantChooser') {
      mermaid += `    class ${id} participant\n`;
    }
  });

  return mermaid;
};

// =====================================
// Helper Functions
// =====================================

/**
 * Sanitizes an ID string for use in AEM XML node names.
 *
 * Replaces any characters that are not alphanumeric, underscore, or hyphen
 * with underscores to ensure valid XML element names.
 *
 * @param {string} id - The original ID string
 * @returns {string} Sanitized ID safe for XML element names
 * @private
 */
const sanitizeId = (id: string): string => {
  return id.replace(/[^a-zA-Z0-9_-]/g, '_');
};

/**
 * Sanitizes an ID string for use in Mermaid diagram node identifiers.
 *
 * Mermaid has stricter ID requirements than XML, so this removes
 * all non-alphanumeric characters.
 *
 * @param {string} id - The original ID string
 * @returns {string} Sanitized ID safe for Mermaid syntax
 * @private
 */
const sanitizeMermaidId = (id: string): string => {
  return id.replace(/[^a-zA-Z0-9]/g, '_');
};

/**
 * Escapes special XML characters in a string.
 *
 * Converts the following characters to their XML entity equivalents:
 * - & → &amp;
 * - < → &lt;
 * - > → &gt;
 * - " → &quot;
 * - ' → &apos;
 *
 * @param {string} str - The string to escape
 * @returns {string} XML-safe escaped string
 * @private
 */
const escapeXml = (str: string): string => {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
};

/**
 * Configuration for AEM workflow node types.
 *
 * @interface AEMNodeConfig
 * @property {string} resourceType - Sling resource type for the node
 * @property {Record<string, string | number | boolean>} attributes - Additional metadata attributes
 * @private
 */
interface AEMNodeConfig {
  /** Sling resource type for the node */
  resourceType: string;
  /** Additional metadata attributes */
  attributes: Record<string, string | number | boolean>;
}

const getAEMNodeConfig = (node: Node): AEMNodeConfig => {
  const configs: Record<string, AEMNodeConfig> = {
    aemStep: {
      resourceType: 'cq/workflow/components/model/participant',
      attributes: {
        'participant': node.data?.participant || 'administrators',
        'timeout': node.data?.timeout || '',
      },
    },
    processStep: {
      resourceType: 'cq/workflow/components/model/process',
      attributes: {
        'PROCESS': node.data?.processHandler || 'com.adobe.granite.workflow.core.process.EchoProcess',
        'PROCESS_AUTO_ADVANCE': 'true',
      },
    },
    branch: {
      resourceType: 'cq/workflow/components/model/or',
      attributes: {},
    },
    emailNotification: {
      resourceType: 'cq/workflow/components/model/process',
      attributes: {
        'PROCESS': 'com.day.cq.workflow.impl.process.EmailNotificationProcess',
        'PROCESS_AUTO_ADVANCE': 'true',
      },
    },
    damUpdate: {
      resourceType: 'cq/workflow/components/model/process',
      attributes: {
        'PROCESS': 'com.day.cq.dam.core.process.CreateAssetProcess',
        'PROCESS_AUTO_ADVANCE': 'true',
      },
    },
    damMetadata: {
      resourceType: 'cq/workflow/components/model/process',
      attributes: {
        'PROCESS': 'com.day.cq.dam.core.process.MetadataProcessorProcess',
        'PROCESS_AUTO_ADVANCE': 'true',
      },
    },
    damTranscode: {
      resourceType: 'cq/workflow/components/model/process',
      attributes: {
        'PROCESS': 'com.day.cq.dam.video.process.VideoThumbnailDownloadProcess',
        'PROCESS_AUTO_ADVANCE': 'true',
      },
    },
    formsProcess: {
      resourceType: 'cq/workflow/components/model/process',
      attributes: {
        'PROCESS': 'com.adobe.aemfd.watchfolder.workflow.api.FPProcessWorkflowStep',
        'PROCESS_AUTO_ADVANCE': 'true',
      },
    },
    pageActivation: {
      resourceType: 'cq/workflow/components/model/process',
      attributes: {
        'PROCESS': 'com.day.cq.wcm.workflow.process.ActivatePageProcess',
        'PROCESS_AUTO_ADVANCE': 'true',
      },
    },
    participantChooser: {
      resourceType: 'cq/workflow/components/model/participant',
      attributes: {
        'participant': node.data?.participant || 'administrators',
      },
    },
    graniteRouting: {
      resourceType: 'cq/workflow/components/model/participant',
      attributes: {
        'participant': node.data?.assignTo || 'administrators',
      },
    },
    callWorkflow: {
      resourceType: 'cq/workflow/components/model/process',
      attributes: {
        'PROCESS': 'com.adobe.granite.workflow.core.job.StartWorkflowProcess',
        'PROCESS_AUTO_ADVANCE': 'true',
        'WORKFLOW_MODEL': node.data?.workflowModel || '',
      },
    },
  };

  return configs[node.type || ''] || {
    resourceType: 'cq/workflow/components/model/process',
    attributes: {},
  };
};

// =====================================
// Download Helper
// =====================================

/**
 * Downloads content as a file in the browser.
 *
 * Creates a temporary Blob URL, triggers a download, and cleans up
 * the resources. Works in all modern browsers.
 *
 * @param {string} content - The file content to download
 * @param {string} filename - Suggested filename for the download
 * @param {string} mimeType - MIME type of the content (e.g., 'application/json')
 *
 * @example
 * // Download JSON
 * downloadFile(jsonString, 'workflow.json', 'application/json');
 *
 * @example
 * // Download XML
 * downloadFile(xmlString, 'workflow.xml', 'application/xml');
 *
 * @example
 * // Download Markdown
 * downloadFile(markdownString, 'workflow-docs.md', 'text/markdown');
 */
export const downloadFile = (
  content: string,
  filename: string,
  mimeType: string
): void => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// =====================================
// Import Functions
// =====================================

/**
 * Imports a workflow from JSON format.
 *
 * Parses an AEMFlow JSON export and returns the nodes and edges
 * ready for use in ReactFlow. Validates the format version and
 * adds necessary properties for the editor.
 *
 * @param {string} jsonString - JSON string exported by AEMFlow
 * @returns {{ nodes: Node[]; edges: Edge[] }} Parsed nodes and edges
 *
 * @throws {SyntaxError} If jsonString is not valid JSON
 * @throws {Error} If format is not 'aemflow-json'
 *
 * @example
 * try {
 *   const { nodes, edges } = importFromJSON(jsonString);
 *   setNodes(nodes);
 *   setEdges(edges);
 * } catch (error) {
 *   console.error('Failed to import workflow:', error);
 * }
 */
export const importFromJSON = (jsonString: string): { nodes: Node[]; edges: Edge[] } => {
  const data = JSON.parse(jsonString);

  if (data.format !== 'aemflow-json') {
    throw new Error('Invalid AEMFlow JSON format');
  }

  return {
    nodes: data.nodes.map((node: any) => ({
      ...node,
      draggable: true,
    })),
    edges: data.edges.map((edge: any) => ({
      ...edge,
      animated: true,
    })),
  };
};

/**
 * Imports a workflow from YAML format.
 *
 * Parses an AEMFlow YAML export using a simple line-based parser.
 * Supports the standard AEMFlow YAML structure with nodes and edges
 * sections.
 *
 * Note: This is a lightweight parser designed specifically for
 * AEMFlow's YAML format. For complex YAML, consider using a
 * full YAML parser library.
 *
 * @param {string} yamlString - YAML string exported by AEMFlow
 * @returns {{ nodes: Node[]; edges: Edge[] }} Parsed nodes and edges
 *
 * @example
 * const yamlContent = `
 * nodes:
 *   - id: "start"
 *     type: startEnd
 *     label: "Start"
 *     isStart: true
 * edges:
 *   - id: "e1"
 *     source: "start"
 *     target: "step1"
 * `;
 * const { nodes, edges } = importFromYAML(yamlContent);
 */
export const importFromYAML = (yamlString: string): { nodes: Node[]; edges: Edge[] } => {
  // Simple YAML parser for our format
  const lines = yamlString.split('\n');
  const nodes: Node[] = [];
  const edges: Edge[] = [];

  let currentSection = '';
  let currentItem: any = null;

  lines.forEach(line => {
    const trimmed = line.trim();

    if (trimmed === 'nodes:') {
      currentSection = 'nodes';
    } else if (trimmed === 'edges:') {
      currentSection = 'edges';
    } else if (trimmed.startsWith('- id:')) {
      // New item
      if (currentItem) {
        if (currentSection === 'nodes') {
          nodes.push({
            ...currentItem,
            draggable: true,
            position: currentItem.position || { x: 200, y: nodes.length * 120 },
          });
        } else if (currentSection === 'edges') {
          edges.push({
            ...currentItem,
            animated: true,
          });
        }
      }
      currentItem = { id: trimmed.replace('- id:', '').trim().replace(/"/g, '') };
    } else if (currentItem && trimmed.includes(':')) {
      const [key, ...valueParts] = trimmed.split(':');
      const value = valueParts.join(':').trim().replace(/"/g, '');
      currentItem[key.trim()] = value === 'true' ? true : value === 'false' ? false : value;
    }
  });

  // Don't forget the last item
  if (currentItem) {
    if (currentSection === 'nodes') {
      nodes.push({
        ...currentItem,
        draggable: true,
        position: currentItem.position || { x: 200, y: nodes.length * 120 },
        data: {
          label: currentItem.label,
          description: currentItem.description,
          participant: currentItem.participant,
          isStart: currentItem.isStart,
        },
      });
    } else if (currentSection === 'edges') {
      edges.push({
        ...currentItem,
        animated: true,
      });
    }
  }

  return { nodes, edges };
};
